### ISSUE TITLE
why are there more README commits in this project?

### ISSUE THREAD

**Issue by nikhilrayaprolu** [timestocome/Test-stock-prediction-algorithms#2]
Hello @timestocome I have started researching upon stock market prediction and came across your project.
Thank You for your work, but I don't understand why you just update the README all the time :P ?

**Comment by timestocome** [comment]
I update the readme with new papers I find, move unread to read and promising ones to the to-code section.

There have been many code updates, but because there are so many small pieces some have been spun off, you'll notice I updated the readme to show links to the repositories where code has been spun off.
