### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ceased-ebc** [timestocome/Test-stock-prediction-algorithms#4]
.

**Comment by timestocome** [comment]
It is not complete. It is a work in progress. It's intended to serve as sample code for people working on their own predictive algorithms and as starter code I use for more complex projects.

Currently I'm looking into several other things, genetic algorithms, reinforcement code.. I had to step back and brush up on TensorFlow as I wasn't able to get Theano to build the next networks on my todo list.

If you're looking for a tool to predict the markets for you this isn't it. If I find the answer I'm keeping it secret, getting rich and buying an island somewhere.

**Comment by WilliamJamesDalrympleWest** [comment]
LOL, love the island remark, no, i was looking am looking for various options to run alongside our existing for correction measures.

**Comment by timestocome** [comment]
What are you using now for tools? 

A friend went on a job interview for a local hedge fund. She came over with a tech test they hand out. It was on spreadsheets. I realized there might be a market here.  (Spreadsheets!?!, are you kidding? ) So I started digging. 

I found a few interesting things, the histograms of bears and bulls are very different. Bulls give a power curve, which is what you'd expect in finance or social data, bears look Gaussian. What I haven't found is a method ( other'n the obvious it looks like a Tulip Bulb Market ) indicator.  I'm still looking for the new 'lipstick' indicator. 

I had some short term prediction success with time series. Nothing earthshaking. 

There's more of a herd behavior now, that always destabilizes and breaks things. The federal government being in a disarray isn't helping either. 

Also on the to do list is to download a bunch of individual stock data and see what, if any, of the financial statement data predicts stock price movement. Maybe it's what we already know? Maybe there's something else in there? Clustering stuff is still pretty dodgy. I'm not sure how much I trust it?

I'm currently working on a robotics project, thinking a lot, and improving my TensorFlow, so it might be a few weeks before the Stock repository gets updated.

**Comment by WilliamJamesDalrympleWest** [comment]
What are you using now for tools?

Autonomous AI (Jean) essentially ML/DL with comprehension backbone, (Invacio), however early stages, although we tested her last week on one of the smaller arms (agnes) and created a 240% inflation on demo funds in the span of 4 days (plus500) i am not satisfied aulthough her accuracy levels (set milestones) returned 70%,80%,90%,95+%, accuracy levels in their respective short/mid range projections, there was a few elements that left a touch to be desired for me,  so we're scaling that out somewhat, and i am considering coupling additional base line algos (where in testing offer anything above 70% accuracy over a period) against hers so she can either learn from or observe where it/she is going wrong and correct it's/her self. 
![screen shot 2017-08-18 at 23 30 14](https://user-images.githubusercontent.com/7057144/29480001-3c4440b4-846d-11e7-9fc0-7dd5aaa54c3e.png)

A friend went on a job interview for a local hedge fund. She came over with a tech test they hand out. It was on spreadsheets. I realised there might be a market here. (Spreadsheets!?!, are you kidding? ) So I started digging.

> being honest my cousin has just joined JPM as a economist, i don't think they even realise how out-gunned they are against AI driven prediction/trading that is beginning to take foot, in reality a analyst has maybe 5 trades in mind and researches before committing, where as AI does that well (in our case) in a very short period of time, i also note were 'bot'/'algo' ai which a lot of who ha has been about but much further on in the stages, however with multiple areas of concerns, so i suspect 5 years of embedding in the systems etc and testing before mainstream uptake.

I found a few interesting things, the histograms of bears and bulls are very different. Bulls give a power curve, which is what you'd expect in finance or social data, bears look Gaussian. What I haven't found is a method ( other'n the obvious it looks like a Tulip Bulb Market ) indicator. I'm still looking for the new 'lipstick' indicator.

> I should probably inject here, although i am involved financially via hedge funds, i am not a specific trader or trained in those regards however, my partner is an ex director level at the NYSE, switched on, runs a private hedge now in retirement and on the project, i wont go in too to much detail on our system as it's still under dev after 5.5 years however will say one of the areas that was pushed a lot was the Ichimoku indicator, also i've attached a document for another indicator flow that will hopefully aid you in your endeavour, also a document that is in relation to baseline algo (in R) which may also aid you, something i've been testing of late before coupling up with some success. 
[Decoding Stock Market with Quant Alphas_source.pdf](https://github.com/timestocome/Test-stock-prediction-algorithms/files/1235795/Decoding.Stock.Market.with.Quant.Alphas_source.pdf)
[ForexTradingBook-Pedraza-Excerpt.pdf](https://github.com/timestocome/Test-stock-prediction-algorithms/files/1235796/ForexTradingBook-Pedraza-Excerpt.pdf)

I had some short term prediction success with time series. Nothing earthshaking.

> what i find is the accuracy and direction as imperative and sort by the biggest movers expected over the proceeding 24 - 72 hours by margin, would be interested to hear more on your results here. 

There's more of a herd behavior now, that always destabilizes and breaks things. The federal government being in a disarray isn't helping either.

> agreed well the market is a placebo state now as far as i am concerned, essentially Trump propping it up, but it's ready to come down, i suspect 18 months.

Also on the to do list is to download a bunch of individual stock data and see what, if any, of the financial statement data predicts stock price movement. Maybe it's what we already know? Maybe there's something else in there? Clustering stuff is still pretty dodgy. I'm not sure how much I trust it?

> We have a lot of the data (TB's) economic, sat, micro, macro, exchange etc coming in from various suppliers, automatically/dynamically, it took some doing, but it's far easier to work of dynamic data than CSV's i can assure you, even short term for testing, you get a clearer picture and see where the entire thing comes apart under strain 

I'm currently working on a robotics project, thinking a lot, and improving my TensorFlow, so it might be a few weeks before the Stock repository gets updated.

Not to worry, i came across, was intrigued, however please do keep me alight, and i hope the above can aid you in your endeavours, if you are ever looking for that private island, or beach land on a island, or close proximity, also drop me a line, i have quite a collection on the andaman sea (indian ocean) and it would be good to have someone else intrigued by systematic approach to the world in touch. 

Kind regards
William

**Comment by timestocome** [comment]
Interesting ideas on Invacio, I love the ideas behind it, many of which I'm trying to look into on a smaller scale. Some of the website seems to be still under construction, but I wandered around the sections you have up and running. Banks are conservative, despite their reputation for being radical when ever the market crashes. That bot that bancrupted the hedge fund a few years back didn't help any. 

I had a chance to look up the Ichimoku indicator. idk. I ran simulations on almost all the common ones ( that had formulas, not 'we know it when we see it' )  and some worked if you mapped them to a lucky starting day. Most don't work, or fail if you change the time window you test them on. I've tried a few ways to use machine learning to find new ones, I've not been pleased with the results. That's still a work in progress. I do think, that like Wolfram's simple rules that had complex results from simple rules, there are simple rules. I haven't found them yet. I have a stack of books on chaos and non-linear dynamics on my shelf, along with ones on genetic algorithms. There's never enough time.

I do think social movements and the market are very entangled and there are simple indicators from the herd behavior of the public that give information on future market movements. Then there's the ever present which drives which? Chicken first or egg first?

Much of what is happening in the US right now is fallout from the 2008/09 crash-bubble that that government totally mishandled. I think it's going to get much worse before it gets better.

Using large amounts of data can show us things we hadn't noticed before, there's been some huge break throughs, especially in medicine. There is also a danger that if you have too much data for the network you can find multiple paths that work and there is no clear way to know which one is the correct one and which path will lead you to ruin. ( see: derivatives, housing bubble ;p) Finding the sweet spot is the challenge. There'll be some more major screw ups because of this.

It's all fascinating.
